# Generated by Django 3.0.5 on 2020-04-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cola',
            name='fecha',
            field=models.DateField(help_text='Fecha en la que se habilitará esta cola.', verbose_name='fecha'),
        ),
    ]
