# Generated by Django 3.0.5 on 2020-04-04 18:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200402_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(blank=True, default=None, help_text='Descripción de la empresa.', max_length=150, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='imagen',
            field=models.URLField(blank=True, help_text='URL donde se encuentra el logotipo de esta sucursal.', null=True, verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Número de teléfono de la sucursal en el formato +50322155879', max_length=128, null=True, region=None, verbose_name='número de teléfono'),
        ),
        migrations.AlterField(
            model_name='cola',
            name='horario',
            field=models.ForeignKey(help_text='Horario en el cual esta cola estará habilitada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.Horario', verbose_name='horario'),
        ),
        migrations.AlterField(
            model_name='cola',
            name='sucursal',
            field=models.ForeignKey(help_text='Sucursal para la que se habilitará esta cola.', on_delete=django.db.models.deletion.CASCADE, to='tickets.Sucursal', verbose_name='sucursal'),
        ),
        migrations.AlterField(
            model_name='cola',
            name='tipo_cola',
            field=models.ForeignKey(help_text='Tipo de cola.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.TipoCola', verbose_name='tipo de cola'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(help_text='Nombre de este departamento.', max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='administrador',
            field=models.ForeignKey(blank=True, default=None, help_text='Administrador del sistema para esta empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='administrador'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(help_text='NIT de la empresa.', max_length=17, verbose_name='nit'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(help_text='Nombre de la empresa.', max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_corto',
            field=models.CharField(help_text='Nombre corto de la empresa.', max_length=50, verbose_name='nombre corto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.ForeignKey(default=None, help_text='Tipo de empresa.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.TipoEmpresa', verbose_name='tipo de empresa'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.IntegerField(choices=[(1, 'DOMINGO'), (2, 'LUNES'), (3, 'MARTES'), (4, 'MIÉRCOLES'), (5, 'JUEVES'), (6, 'VIERNES'), (7, 'SÁBADO')], default=2, help_text='Día en que se tiene este horario.', validators=[django.core.validators.MinValueValidator(1, 'La opción seleccionada es inválida'), django.core.validators.MaxValueValidator(7, 'La opción seleccionada es inválida')], verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='sucursal',
            field=models.ForeignKey(help_text='Sucursal que atiende en este horario.', on_delete=django.db.models.deletion.CASCADE, to='tickets.Sucursal', verbose_name='sucursal'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(help_text='Departamento', on_delete=django.db.models.deletion.CASCADE, to='tickets.Departamento', verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(help_text='Nombre de este municipio.', max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección.', max_length=200, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa a la que pertenece esta sucursal.', on_delete=django.db.models.deletion.CASCADE, to='tickets.Empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='municipio',
            field=models.ForeignKey(help_text='Municipio en el que se encuentra esta sucursal.', on_delete=django.db.models.deletion.CASCADE, to='tickets.Municipio', verbose_name='municipio'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(help_text='Nombre de la sucursal.', max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cajero',
            field=models.ForeignKey(help_text='Cajero que despachó este ticket.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajero', to=settings.AUTH_USER_MODEL, verbose_name='cajero'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cant_intentos',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cantidad de intentos que se hizo para despachar este ticket.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3, 'Solo se permiten 3 intentos.')], verbose_name='cantidad de intentos'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente que solicita este ticket.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cola',
            field=models.ForeignKey(help_text='Cola a la que se asigna este ticket.', on_delete=django.db.models.deletion.CASCADE, to='tickets.Cola', verbose_name='cola'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ESPERA'), (2, 'ACTIVO'), (3, 'PASO'), (4, 'VENCIDO'), (5, 'RETIRADO')], default=1, help_text='Estado actual de este (ticket ESPERA = 1), (ACTIVO = 2),  (PASO = 3), (VENCIDO = 4) ó (RETIRADO = 5).', validators=[django.core.validators.MinValueValidator(1, 'La opción seleccionada es inválida'), django.core.validators.MaxValueValidator(5, 'La opción seleccionada es inválida')], verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='numero',
            field=models.CharField(help_text='Número del ticket.', max_length=10, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='tipocola',
            name='capacidad',
            field=models.PositiveSmallIntegerField(help_text='Capacidad máxima de esta cola.', verbose_name='capacidad'),
        ),
        migrations.AlterField(
            model_name='tipocola',
            name='descripcion',
            field=models.CharField(blank=True, default=None, help_text='Descripción de esta cola.', max_length=150, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='tipocola',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa a la que pertenece este tipo de cola.', on_delete=django.db.models.deletion.CASCADE, to='tickets.Empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='tipocola',
            name='tipo',
            field=models.CharField(help_text='Nombre de este tipo de cola.', max_length=30, verbose_name='tipo de cola'),
        ),
        migrations.AlterField(
            model_name='tipoempresa',
            name='tipo',
            field=models.CharField(help_text='Tipo de empresa.', max_length=30, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CAJERO'), (2, 'USUARIO'), (3, 'ADMINISTRADOR')], default=2, help_text='ROL del usuario (CAJERO = 1), (USUARIO = 2), o (ADMINISTRADOR = 3)', validators=[django.core.validators.MinValueValidator(1, 'La opción seleccionada es inválida'), django.core.validators.MaxValueValidator(3, 'La opción seleccionada es inválida')], verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, default=None, help_text='Sucursal, en el caso que este usuario tenga el rol "CAJERO".', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Sucursal', verbose_name='sucursal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Número de teléfono en el formato +50377234521', max_length=128, null=True, region=None, verbose_name='número de teléfono'),
        ),
    ]
